Answering a question shouldn't change scroll position
ucfopen/Obojobo pull request #1123
Opened 2020-01-29 22:20 UTC by ctcuff

Resolves #1109.

2020-02-05 22:11 UTC, ctcuff commented
I tested this in Chrome but this still needs to be tested in FireFox and Safari

2020-03-10 19:34 UTC, zachberry requested changes
I tested this out, and it seems to be much more solid, but seemingly randomly it still jumps around. I may need to dig in more and see if something else is taking over.

Here's a document I was using to test jumping around:

```json
 {
    "id": "a4b0748a-4df0-4c5d-8746-76b55071b8b5",
    "rev": "f1da00f6-cc6b-4217-9368-1b09c748716d",
    "type": "ObojoboDraft.Modules.Module",
    "index": 0,
    "content": {
      "start": null,
      "title": "My Obojobo Module Title"
    },
    "draftId": "916d8bb3-138f-4891-9a88-d3fe090034ce",
    "metadata": {},
    "contentId": "adbeb0df-6f8b-444d-8106-b549ae6ac9ff",
    "Rev": "adbeb0df-6f8b-444d-8106-b549ae6ac9ff",
    "children": [
      {
        "id": "0bc482e7-490c-4203-b108-ad24a54e49e0",
        "type": "ObojoboDraft.Sections.Content",
        "index": 0,
        "content": {},
        "metadata": {},
        "children": [
          {
            "id": "99507ee8-5c0b-428f-ae4a-a7b404ac8eec",
            "type": "ObojoboDraft.Pages.Page",
            "content": {
              "title": "Example content page"
            },
            "children": [
              {
                "id": "ad214bf1-ca98-45bf-b2d0-5534a4e16f7e",
                "type": "ObojoboDraft.Chunks.Heading",
                "content": {
                  "textGroup": [
                    {
                      "data": {
                        "align": "left"
                      },
                      "text": {
                        "value": "Your Title Here",
                        "styleList": []
                      }
                    }
                  ],
                  "headingLevel": 1
                },
                "children": []
              },
              {
                "id": "56b91f37-add4-4cd8-8185-d127ec60b3c0",
                "type": "ObojoboDraft.Chunks.Text",
                "content": {
                  "textGroup": [
                    {
                      "data": {
                        "align": "left",
                        "indent": 0
                      },
                      "text": {
                        "value": "Your content here",
                        "styleList": []
                      }
                    }
                  ]
                },
                "children": []
              },
              {
                "id": "deaad283-3da3-42b5-85eb-99128f2fb3bc",
                "type": "ObojoboDraft.Chunks.Question",
                "content": {
                  "type": "default",
                  "solution": {
                    "id": "01985def-1ad6-4abd-84a6-626e9d868bcc",
                    "type": "ObojoboDraft.Pages.Page",
                    "content": {},
                    "children": [
                      {
                        "id": "14e870c9-f31c-4311-afeb-e34550836bb2",
                        "type": "ObojoboDraft.Chunks.Text",
                        "content": {
                          "textGroup": [
                            {
                              "data": {
                                "indent": 0
                              },
                              "text": {
                                "value": "a",
                                "styleList": []
                              }
                            }
                          ]
                        },
                        "children": []
                      }
                    ]
                  }
                },
                "children": [
                  {
                    "id": "fe8fb3e0-261b-44e3-a978-c5c92d4b1bb9",
                    "type": "ObojoboDraft.Chunks.Text",
                    "content": {
                      "textGroup": [
                        {
                          "data": {
                            "indent": 0
                          },
                          "text": {
                            "value": "a",
                            "styleList": []
                          }
                        }
                      ]
                    },
                    "children": []
                  },
                  {
                    "id": "95308fcf-c6a8-4bbc-abb8-8749deb6dc69",
                    "type": "ObojoboDraft.Chunks.MCAssessment",
                    "content": {
                      "shuffle": true,
                      "responseType": "pick-one"
                    },
                    "children": [
                      {
                        "id": "a0c8627d-7c34-47bc-af09-488d2aabfdea",
                        "type": "ObojoboDraft.Chunks.MCAssessment.MCChoice",
                        "content": {
                          "score": 0
                        },
                        "children": [
                          {
                            "id": "c0a3ace4-063e-4d22-b975-4f91334e7668",
                            "type": "ObojoboDraft.Chunks.MCAssessment.MCAnswer",
                            "content": {},
                            "children": [
                              {
                                "id": "170416fe-5f43-4e99-9e66-0461685d4f73",
                                "type": "ObojoboDraft.Chunks.Text",
                                "content": {
                                  "textGroup": [
                                    {
                                      "data": {
                                        "indent": 0
                                      },
                                      "text": {
                                        "value": "a",
                                        "styleList": []
                                      }
                                    }
                                  ]
                                },
                                "children": []
                              }
                            ]
                          },
                          {
                            "id": "71af010b-237c-4850-add6-858ae12d0aae",
                            "type": "ObojoboDraft.Chunks.MCAssessment.MCFeedback",
                            "content": {},
                            "children": [
                              {
                                "id": "09488c72-c187-4777-91a9-82d2683ba626",
                                "type": "ObojoboDraft.Chunks.Text",
                                "content": {
                                  "textGroup": [
                                    {
                                      "data": {
                                        "indent": 0
                                      },
                                      "text": {
                                        "value": "a",
                                        "styleList": []
                                      }
                                    }
                                  ]
                                },
                                "children": []
                              }
                            ]
                          }
                        ]
                      },
                      {
                        "id": "f2fb704c-ff3f-434a-87a9-c1ea0d8d6565",
                        "type": "ObojoboDraft.Chunks.MCAssessment.MCChoice",
                        "content": {
                          "score": 0
                        },
                        "children": [
                          {
                            "id": "f73fc796-6829-4be9-a91e-85c620269c0e",
                            "type": "ObojoboDraft.Chunks.MCAssessment.MCAnswer",
                            "content": {},
                            "children": [
                              {
                                "id": "cfd46c12-4f86-4f10-ab02-dc0faabcfe34",
                                "type": "ObojoboDraft.Chunks.Text",
                                "content": {
                           [...]

2020-09-29 14:28 UTC, zachberry approved these changes
I merged in dev/14 and re-tested this in Chrome, FF and Safari and it seems to be working great. Perhaps I tested it incorrectly the first time (likely) or something's changed with the code between then and now. Anyway, assuming the tests are good this gets my LGTM. Note to self: Need to add documentation about the `preventScroll` option in the `focus:component` event (And make an issue to add that option to the editor UI)

2020-09-29 15:41 UTC, jpeterson976 approved these changes
LGTM! Tested in Chrome, FF, and Safari as well.

2020-09-29 20:58 UTC, merged