Numeric Questions
ucfopen/Obojobo pull request #1408
Opened 2020-07-10 14:23 UTC by zachberry

2020-08-11 16:59 UTC, zachberry commented
In general, these are the areas where the tests need updating/added:

* [ ] - Changes to Modals (ModalUtil, Modal container, React portals, new classes)
* [ ] - Add tests to new NumericAssessment classes (viewer, editor, components, registration)
* [ ] - Add tests for new assessment classes (AssessmentStateMachine, AssessmentUtil / Store changes, Assessment Dialog, server side)
* [ ] - Updates to FocusUtil
* [ ] - New failing tests in EditorApp
* [ ] - Failing tests in Viewer/util/api.js and APIUtil
* [ ] - Remove any tests relating to in-answer units (NumericEntryRange, etc)
* [ ] - Updates to changes in the numeric classes (Decimal, Binary, etc)
* [ ] - Updates to QuestionUtil
* [ ] - Failing tests in ViewerApp due to the new mutation observer used in portal modals
* [ ] - Changes to Question
* [ ] - Failing tests in ValueRange

Or, in terms of files (This may not be including files with no tests yet, also excludes lint errors):

* [ ] - packages/obonode/obojobo-chunks-question-bank/editor-component.test.js
* [ ] - packages/obonode/obojobo-chunks-math-equation/editor-component.test.js
* [ ] - packages/obonode/obojobo-chunks-multiple-choice-assessment/MCChoice/viewer-component.test.js
* [ ] - packages/obonode/obojobo-chunks-question/viewer-component.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/Viewer/stores/question-store.test.js
* [ ] - packages/obonode/obojobo-sections-assessment/viewer-component.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/__tests__/numerics/fractional.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/editor.test.js
* [ ] - packages/obonode/obojobo-chunks-multiple-choice-assessment/viewer-component.test.js (5.132 s)
* [ ] - packages/app/obojobo-document-engine/__tests__/Viewer/stores/assessment-store.test.js (5.422 s)
* [ ] - packages/obonode/obojobo-chunks-break/editor-component.test.js
* [ ] - packages/obonode/obojobo-chunks-action-button/viewer-component.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/__tests__/range/value-range.test.js
* [ ] - packages/obonode/obojobo-chunks-abstract-assessment/Choice/editor-component.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/oboeditor/components/visual-editor.test.js (6.366 s)
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/__tests__/numerics/hexadecimal.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/__tests__/numerics/scientific.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/__tests__/numerics/binary.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/oboeditor/components/navigation/more-info-box.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/__tests__/rule/numeric-rule-outcome.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/__tests__/numerics/decimal.test.js
* [ ] - packages/obonode/obojobo-sections-assessment/components/full-review/index.test.js
* [ ] - packages/obonode/obojobo-sections-assessment/components/post-test/index.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/__tests__/numerics/octal.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/Viewer/util/api-util.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/__tests__/range/numeric-entry-range.test.js
* [ ] - packages/obonode/obojobo-chunks-figure/editor-component.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/Viewer/stores/focus-store.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/oboeditor/components/triggers/trigger-list-modal.test.js
* [ ] - packages/obonode/obojobo-chunks-question/editor-component.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/__tests__/numerics/numeric.test.js
* [ ] - packages/obonode/obojobo-chunks-action-button/editor-component.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/__tests__/rule/numeric-rule.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/oboeditor/components/node/editor-component.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/oboeditor/components/editor-app.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/Viewer/util/question-util.test.js
* [ ] - packages/obonode/obojobo-chunks-multiple-choice-assessment/editor-component.test.js
* [ ] - packages/obonode/obojobo-chunks-iframe/editor-component.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/NumericAnswer/editor-component.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/__tests__/entry/numeric-matches.test.js
* [ ] - packages/obonode/obojobo-chunks-table/editor-component.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/__tests__/evaluation/numeric-answer-results.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/NumericAnswer/numeric-option.test.js
* [ ] - packages/obonode/obojobo-chunks-abstract-assessment/Choice/changes/normalize-node.test.js
* [ ] - packages/obonode/obojobo-chunks-question/server/question.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/common/components/modal/simple-dialog.test.js
* [ ] - packages/obonode/obojobo-chunks-multiple-choice-assessment/editor-registration.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/Viewer/util/assessment-util.test.js
* [ ] - packages/obonode/obojobo-chunks-youtube/editor-component.test.js
* [ ] - packages/obonode/obojobo-chunks-question/converter.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/editor-component.test.js
* [ ] - packages/obonode/obojobo-chunks-heading/converter.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/oboeditor/components/toolbars/file-toolbar.test.js
* [ ] - packages/obonode/obojobo-sections-assessment/server/events.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/Viewer/util/api.test.js
* [ ] - packages/obonode/obojobo-sections-assessment/components/attempt-incomplete-dialog.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/common/components/modal/prompt.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/converter.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/common/components/more-info-button.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/common/components/modal-container.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/common/util/focus-util.test.js
* [ ] - packages/obonode/obojobo-chunks-abstract-assessment/Feedback/editor-component.test.js
* [ ] - packages/obonode/obojobo-chunks-multiple-choice-assessment/adapter.test.js
* [ ] - packages/obonode/obojobo-chunks-question/adapter.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/Viewer/components/viewer-app.test.js (14.426 s)
* [ ] - packages/obonode/obojobo-chunks-multiple-choice-assessment/mc-assessment-explanation.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/NumericChoice/viewer-component.test.js
* [ ] - packages/obonode/obojobo-chunks-multiple-choice-assessment/editor.test.js
* [ ] - packages/obonode/obojobo-chunks-question-bank/editor-component.test.js
* [ ] - packages/obonode/obojobo-chunks-math-equation/editor-component.test.js
* [ ] - packages/obonode/obojobo-chunks-multiple-choice-assessment/MCChoice/viewer-component.test.js
* [ ] - packages/obonode/obojobo-chunks-question/viewer-component.test.js
* [ ] - packages/app/obojobo-document-engine/__tests__/Viewer/stores/question-store.test.js
* [ ] - packages/obonode/obojobo-sections-assessment/viewer-component.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/__tests__/numerics/fractional.test.js
* [ ] - packages/obonode/obojobo-chunks-numeric-assessment/editor.test.js
* [ ] - packages/obonode/obojobo-chunks-multiple-choice-assessment/viewer-component.test.js (5.132 s)
* [ ] - packages/app/obojobo-document-engine/__tests__/Viewer/stores/assessment-store.test.js (5.422 s)
* [ ] - packages/obonode/obojobo-chunks-break/editor-component.test.js [...]

2021-04-13 20:18 UTC, zachberry commented
Here's everything in this branch:

* Adds obojobo-chunks-abstract-assessment, a new base class for numeric and mc assessments
* Adds obojobo-chunks-numeric-assessment
* Adds "xstate" dependency
* Updates "common/components/button.js" with new `isSubmittable` prop. If true the button is changed from `<button type="button"` to `<button type="submit"`. This is necessary to use <Button> in a form as a submit button 
* Updates modals to support a new form of modals using React portals. "common/components/modal-container.js" has been updated to support this new modal format. Implementing React portal modals was necessary to implement the new assessment modal. This updates based on assessment state, and sending props to a modal was only possible via portals.
* Adds "common/components/modal-portal.js" as a way to tap into the new React portal modal system. Any child of <ModalPortal> will be appended to the main React portal in viewer-app.
* "common/components/modal/dialog.js" no longer requires the `buttons` prop, allowing you to create modals without buttons. This is used in the new assessment modal to create loading modals where there is no input expected from the user.
* Adds aria labels to "common/components/modal/modal.js" to notify the user when they've reached the end or beginning of the dialog tab order. Also focuses on the dialog when displayed. Also updates modal style to use box-sizing: border-box.
* Updates "common/components/more-info-button" to use a randomly generated DOM id, ensuring that more than one more-info-button can appear on the screen without invalid html.
* Adds "common/components/throbber.js" to be used as a rotating loading circle icon
* Adds "common/util/timeout-promise.js", a new function that can be used to call a promise, but automatically reject the promise after a given ms delay. This is used in the updates to assessment - Now when answering an assessment question the question goes into a disabled state where the user can't interact with the question. Once the server responds with a 200 OK message the question is re-enabled. However in case of network issues that disabled state would last indefinately. timeoutPromise essentially allows assessment to give up on hearing back from the server and gives the student a chance to re-interact with the question.
* Adds "common/util/wait-for-element.js", a function which returns a promise that resolves when a DOM element exists in the document. This is used by ModalPortal - when ModalPortal is mounted the react portal container DOM element doesn't yet exist. waitForElement allows ModalPortal to wait until the portal exists to then render.
* Updates "oboeditor/components/editor-app.js" to use <Throbber /> instead of "Loading..."
* Adds a "is-selected" or "is-not-selected" class to base editor-components. This is needed to ensure selected chunks in the visual editor are at a higher z-index, allowing any associated controls to appear above other nodes.
* Adds a min-width to the Visual Editor, fixing layout issues when the browser window is too small
* Updates "viewer/assessment/assessment-score-report-view.js" to show a random positive emoji when scoring 100%.
* Moves the review flag for questions into its own "viewer/components/flag.js" component
* Adds a new base component which all question assessment components now extend - "viewer/components/obo-question-assessment-component.js". This base component includes several methods to be implemented by the super class.
* Adds a new base component for Questions - "viewer/components/obo-question-component". Expects the Question to implement a method to retrieve the assessment model from its children
* Splits up functionality in assessment-store into a few different files. Server communication and a few other housekeeping methods are now in "viewer/stores/assessment-state-helpers.js". The flow of assessment is moved into "viewer/stores/assessment-state-machine.js". Assessment store then has been reduced to managing assessment state and communicating with the state machine. In general the flow is now this: Something in the system calls an AssessmentUtil method, which fires an event that AssessmentStore listens to. AssessmentStore then sends an action to AssessmentStateMachine. AssessmentStateMachine updates its state (and optionally talks to the server via AssessmentStateHelpers), then updates assessment state accordingly.
* Assessment Store now allows for multiple importable scores and multiple assessment summaries, one for each assessment. While we currently only support one assessment, this brings these data structures in line with how the other data structures work in Assessment Store
* Adds "viewer/stores/assessment-store/assessment-network-states.js", all of the possible states (or steps) for the new assessment state machine
* Adds "viewer/stores/assessment-store/assessment-network-states.js", all of the possible actions that the assessment state machine responds to.
* Adds `region` to focus store. Region is an optional string used to inform a component what part of itself it should focus on when its `focusOnContent` method is called. This was implemented so the focus store could be used to focus specifically on the answers portion of a question (rather than just the question itself).
* Updates to nav-store to help with the initial navigation target. These changes were necessary with the new assessment machine flow to be able to still direct the user to the assessment section if they are resuming an attempt. Also renames the `nav:afterNavChange` event to `nav:targetChanged` event, following the other examples of post-action events ending in "ed".
* Question Store has been updated. `question:setResponse` no longer sends the event to the server right away. It requires `sendResponseImmediately` to be true to emulate the old behavior. `question:sendResponse` has been added to send the `question:setResponse` event manually. `question:forceSendAllResponses` has been added to send all unsent `question:setResponse` events for a given context. These changes were needed as numeric questions need to wait for a student to finish inputting their answer before the answer can be sent to the server. Existing multiple choice questions could send their responses right away as the act of answering the question is a simple click on the radio button. To this end, "viewer/stores/question-store/question-response-send-states.js" maintains the network state of a response being sent to the server. Additionally, more information has been added to the response data kept in question store - `details` (arbitrary data, used by numeric questions to keep detailed information about their responses as calculated by the numeric score classes), `feedbackText` - this is the text such as "Correct!" that is displayed in a green or red pill after answering a question, and `detailedText`, which is text displayed at the bottom of a question after answering it (used by pick-all multiple choice questions to notify the user why they got a pick-all question wrong - see PICK_ALL_INCORRECT_MESSAGE)
* AssessmentUtil gets several new methods for dealing with Assessment summaries and Assessment state machines. Fixed a bug with AssessmentUtil.getAttemptsRemaining where the nav menu (once place it's used) would show the incorrect number of attempts remaining if a score was imported - the assessment summary (which is now where this method pulls from) was correct but the full assessment state could be not updated from the server and be incorrect.
* AssessmentUtil adds `getCurrentAttemptQuestionsStatus`, used to return an object describing the states of questions for an assessment - for example - any questions that are empty, being sent to the server, or have already been recorded. This method is used in `getCurrentAttemptStatus`, which boils down the assessment to one of the possible "CurrentAssessmentStates". This is used to determine what to do when a user attempts to submit an assessment.  [...]

2021-04-13 23:28 UTC, zachberry commented
UCF Staff Only: Here's a video review of me showing off the new user-facing features - https://ucf-my.sharepoint.com/:v:/g/personal/zberry_ucf_edu/ERzNs1Lx0D1KhN9nlNZy7NYBL47lCy7Xf9C-43lEokI3hQ?e=yjk3aR .  This revealed a bug with focus inputs which is now a known issue I suppose - I left it in because it's humorous and you can laugh at my pain. Will work on a fix, but the rest of the video still applies.

2021-04-14 18:30 UTC, zachberry commented on packages/obonode/obojobo-chunks-question/schema.js
> +import { Block } from 'slate'
Looks like a left-over from the old slate, deleting

2021-04-14 18:30 UTC, zachberry commented on packages/obonode/obojobo-chunks-question/viewer-component.js
> +	renderResponseSendState(responseSendState) {
This code is unused, so deleting

2021-04-14 18:35 UTC, zachberry commented on packages/app/obojobo-document-engine/src/scripts/viewer/stores/assessment-store.js
> +		const unfinishedAttempt = ext.assessmentSummary[0] || null //@TODO - Correct?
This code wasn't being used, deleting

2021-04-14 21:30 UTC, zachberry commented
> This revealed a bug with focus inputs which is now a known issue I suppose

I believe I've pushed a fix for the bug you see in the video

2021-04-15 16:07 UTC, zachberry commented
UCF Staff Only: Here are videos where I go over the PR since it's such a monstrosity

Part 1: https://ucf-my.sharepoint.com/:v:/g/personal/zberry_ucf_edu/EWAjr-VhlZ5DkyefAqX1i1QB9XyPOA2k03eonq0MwXvsEg?e=0HOaKZ
Part 2: https://ucf-my.sharepoint.com/:v:/g/personal/zberry_ucf_edu/EeLETvnv_91EvkBx87meJFwBPcCFHQRAhvj8GGx32FmmRw?e=vxDcyZ

2021-04-15 19:52 UTC, zachberry commented
Pushed a change which no longer shows the error dialog when you submit an invalid response in numeric questions, like "*". Instead it now shows DOM form validation on the input when submitting. To achieve this, OboQuestionAssessmentComponent has a new `checkIfResponseIsValid`, which is called when a question is submitted. If it returns false then the response is scored/graded. That method also allows the question assessment component to show any validation, which the numeric assessment viewer component does

2021-04-20 22:05 UTC, iturgeon requested changes
only made it up to `obojobo-document-engine/src/scripts/viewer/index.js`  but submitting now since I'll be unable to contribute tomorrow.

2021-04-20 22:15 UTC, zachberry commented on packages/app/obojobo-document-engine/src/scripts/common/components/throbber.js
> +import './throbber.scss'
I have no objections

2021-04-20 22:16 UTC, zachberry commented on packages/app/obojobo-document-engine/src/scripts/common/components/throbber.js
> +				</svg>
Agree, I'll make a note in our style guide as well

2021-04-21 18:37 UTC, zachberry commented on packages/app/obojobo-document-engine/src/scripts/common/components/throbber.js
> +				</svg>
https://github.com/ucfopen/Obojobo/wiki/Developer-Code-Style-Guide#prefer-destructured-props

2021-04-22 14:46 UTC, iturgeon commented on packages/app/obojobo-document-engine/src/scripts/viewer/components/viewer-app.js
> +			return ViewerAPI.postEvent({
updated, I missed a word, this was intentionally _not_ returning a promise.

2021-04-26 14:00 UTC, maufcost commented
Maybe an edge case: when no possible answers are given to numeric questions, the viewer displays this error message:

![obo](https://user-images.githubusercontent.com/39862359/116094977-fcf17880-a675-11eb-8ecb-72299c631a83.gif)

It does not hinder any functionalities, but perhaps leaves authors and their students asking "why" it happened. Some solutions I thought of:
- Display a better error message (E.g. "No possible answers were given to this question").
- Or perhaps force numeric questions to have at least one possible answer (just like we force multiple choice questions to be correct or incorrect).

2021-04-26 15:06 UTC, zachberry commented
> Maybe an edge case: when no possible answers are given to numeric questions, the viewer displays this error message:
> 
> ![obo](https://user-images.githubusercontent.com/39862359/116094977-fcf17880-a675-11eb-8ecb-72299c631a83.gif)
> 
> It does not hinder any functionalities, but perhaps leaves authors and their students asking "why" it happened. Some solutions I thought of:
> 
> * Display a better error message (E.g. "No possible answers were given to this question").
> * Or perhaps force numeric questions to have at least one possible answer (just like we force multiple choice questions to be correct or incorrect).

I'm having trouble replicating that exact error, but there is an issue where you can have a Numeric Question with no answer choices. It's tough because if it's a survey question then you don't need any answer choices. I discovered another issue while digging in to this too - The button to add a question explanation still is showing up with the survey question option enabled, which it should be disabled. And, if you do manage to give the question an explanation and then turn it into a survey question later the explanation will still show up in the viewer. I'm leaving this comment as a reminder to myself to resolve these issues.

2021-04-26 19:37 UTC, jpeterson976 commented
I found a few cases that cause the page with the question to produce an error and give a white screen:

- Including only letters in the answer, with some exceptions. It seems starting the string with b will let it through in some cases but I haven't been able to narrow down exactly what causes it. It seems to have something to do with what letters you use and the length of the string.
- Having only `#`, `$`, `0x`, or `0o` as the answer with no numbers after the prefix. `0b` doesn't result in the error though, and seems to only accept itself as a correct answer.
- Mistyped/incomplete scientific notation, such as `1e`, `1.23x10^`, `1.23*10`, or `1.23x`. 
- Incomplete fraction (`22/`) or a decimal in a fraction (`1.23/3`).
- Including spaces.
- An empty answer.

These are obviously invalid options anyway based on the help button examples in the viewer, so it might do to have some sort of validation in the editor component to make sure all the answer choices are good.

2021-04-26 20:14 UTC, zachberry commented
> I found a few cases that cause the page with the question to produce an error and give a white screen:
> 
> * Including only letters in the answer, with some exceptions. It seems starting the string with b will let it through in some cases but I haven't been able to narrow down exactly what causes it. It seems to have something to do with what letters you use and the length of the string.
> * Having only `#`, `$`, `0x`, or `0o` as the answer with no numbers after the prefix. `0b` doesn't result in the error though, and seems to only accept itself as a correct answer.
> * Mistyped/incomplete scientific notation, such as `1e`, `1.23x10^`, `1.23*10`, or `1.23x`.
> * Incomplete fraction (`22/`) or a decimal in a fraction (`1.23/3`).
> * Including spaces.
> * An empty answer.
> 
> These are obviously invalid options anyway based on the help button examples in the viewer, so it might do to have some sort of validation in the editor component to make sure all the answer choices are good.

Good call, I'm tracking this in #1792

2021-04-27 15:54 UTC, merged