Shows assessment scores and attempts in nav
ucfopen/Obojobo pull request #1494
Opened 2020-08-31 18:24 UTC by jpeterson976

Resolves #541 

Adds score and attempt information for assessments into the nav menu.

2020-09-01 15:19 UTC, ctcuff commented on packages/app/obojobo-document-engine/src/scripts/viewer/components/nav.js
> +		}
_SUPER_ minor nitpick but you could simplify this a bit:

```javascript
return (
	<li key={index} onClick={this.onClick.bind(this, item)} className={className}>
		{this.renderLinkButton(item.label, ariaLabel, isItemDisabled, item.id)}
		{item.flags.assessment ? (
			<span className="assessment-info">{this.getAssessmentInfo(item)}</span>
		) : null}
		{lockEl}
	</li>
)
```

2020-09-02 20:15 UTC, vutoan1245 approved these changes
Looks nice. I don't see any problem.

2020-09-04 19:56 UTC, zachberry requested changes
This hardcodes some assessment logic inside the nav, which I would rather move out. Ideally I think the assessment's viewer.js's `getNavItem` could return a line of text instead of generating the attempts line inside nav. However, that would be a pretty significant refactor of the nav to get that to work, and there's lots of existing changes I want to make in the nav so it would be a can of worms.

So all that said, I think this is a nice improvement - I'm thinking we push ahead and I'll make an additional issue for the refactor for us to tackle later.

I did find a few things:
1. It's possible to have unlimited attempts - you can make that happen by editing a module in XML, finding the Assessment tag, and changes attempts to `unlimited`. Then the number of attempts in the viewer is set to Infinity. So you'll want to check for that case and write "Unlimited" instead.
2. My preference would be to keep the score line the same even when the Assessment section is clicked on and turns the label to bold blue. Mockup:

![image](https://user-images.githubusercontent.com/73479/92280332-25e6b280-eec7-11ea-8756-e3a59e7b61f9.png)

2020-09-10 16:02 UTC, iturgeon commented
someone's using windows :) @jpeterson976 

`.DS_Store` file made it in to a commit.  remove and add `.DS_Store` to the .gitignore

2020-09-10 17:08 UTC, iturgeon approved these changes

2020-09-10 17:09 UTC, merged