Triple-clicking selection issue
ucfopen/Obojobo pull request #1585
Opened 2020-10-07 16:02 UTC by vutoan1245

Fixes #1550 

Note: This is an open Slate issue. I am fine with disregarding this PR and wait for Slate to fix it.

Problem: triple-clicking causes selection to bleed into the beginning of the node below it. It doesn't happen in Firefox.
Solution: if triple-click happens and selection ends at the beginning -> reduce selection by 1
https://docs.slatejs.org/api/transforms#transforms-move-editor-editor-options

2020-10-12 18:22 UTC, zachberry requested changes
This works great except for one case I found - when triple clicking on the last line of a question the selection disappears

2020-10-19 15:07 UTC, vutoan1245 commented
@zachberry It seems the problem with triple clicking in a question is a separate issue.

2020-12-18 20:37 UTC, zachberry approved these changes
I spent a long time seeing if I could come up with another way to handle the bug when selecting the last line of a question but as far as I could tell the selection is simply not set (for whatever internal Slate reason) when triple clicking the last line of a Question. Since this PR otherwise is an improvement I'm thinking we go ahead and ship, and hope that a future Slate release natively fixes the issue and we can remove this workaround.

2021-02-09 19:15 UTC, ctcuff approved these changes
LGTM, although there's one super tiny edge case: you can still get multiple selections by triple clicking an empty node:

<img width="886" alt="Screen Shot 2021-02-09 at 2 10 44 PM" src="https://user-images.githubusercontent.com/7400747/107415038-dc873880-6ae0-11eb-8652-fa3f39af66d3.png">

Although, approving since I'm not sure if this is something we can fix, may just have to wait for slate to resolve it.

2021-02-23 15:22 UTC, merged