Adds prevent scroll toggle for focus:component event
ucfopen/Obojobo pull request #1615
Opened 2020-11-23 19:40 UTC by jpeterson976

Resolves #1570

If both animate scroll and prevent scroll are turned on, then animate scroll will take over and prevent scroll will be ignored. I'll add this behavior to the documentation for now.

2020-11-30 14:16 UTC, maufcost approved these changes
Looking good on Safari, Chrome, and Firefox. Great job! There are a few times when the trigger modal is completely blurred, but I tested it before your changes and as it turns out, this "blur bug" was already there. I will talk to Zac about it and this will most probably be on another issue.

2021-01-14 22:26 UTC, zachberry requested changes
(I merged in dev/16)

This is perfect, the only issue I found was weird - if you has scrollbars always set to show up and had enough triggers/actions to get them to show up in the dialog then the label for the combobox would move down a line. I cut out a word as a cheap way to get it to fit.

Anyway, blah blah, LGTM!

2021-01-26 18:45 UTC, zachberry approved these changes

2021-02-03 14:17 UTC, maufcost approved these changes
Everything looks good now. Good job, Jacob!

2021-02-03 22:20 UTC, merged