Highlights newly created module
ucfopen/Obojobo pull request #1630
Opened 2020-12-14 18:59 UTC by jpeterson976

Fixes #1510 

Grabs the draftId of the newly created module and highlights it in the dashboard.

2020-12-17 19:21 UTC, ctcuff approved these changes
Super minor CSS issue but looks good! Tested in Chrome, FF, and Safari.

2020-12-17 19:21 UTC, ctcuff commented on packages/app/obojobo-repository/shared/components/module.scss
> +		font-weight: bold;
Looks like setting the font-weight here also affects the font-weight of the buttons in the module's menu

2020-12-18 14:56 UTC, zachberry requested changes
This is awesome! Marking as 'request changes' based on what @ctcuff found - but once that css issue is resolved I'll approve

2021-01-14 19:08 UTC, zachberry approved these changes
(I merged in dev/16)

LGTM!

2021-01-21 14:52 UTC, merged