Fixes viewer crash when loading assessment with katex
ucfopen/Obojobo pull request #1633
Opened 2020-12-16 19:39 UTC by ctcuff

Katex is injected when starting/resuming an assessment since it might not be loaded when the document is first rendered.

Fixes #1604

2020-12-17 14:27 UTC, maufcost reviewed
The viewer is not crashing anymore, but I don't think Katex equations are loading correctly on the assessment (I might be doing something incorrectly). Could you try with `\overleftrightarrow{AB}`, for example, and let me know if it works on your end?

![Latex Issue](https://user-images.githubusercontent.com/39862359/102499934-278d4e00-4052-11eb-8022-6de33d4481e8.png)

2020-12-17 14:48 UTC, maufcost requested changes
As it turns out, I had not switched branches....
I tried with a simple latex command like `\overleftrightarrow{AB}` and it renders **perfectly** on the page, but as soon as I submit a response to a question, the viewer crashes again :(

2020-12-17 17:40 UTC, ctcuff commented
> As it turns out, I had not switched branches....
> I tried with a simple latex command like `\overleftrightarrow{AB}` and it renders **perfectly** on the page, but as soon as I submit a response to a question, the viewer crashes again :(

Good catch! Turns out I forgot to inject katex when rendering the assessment review. Should _hopefully_ be fixed now.

2020-12-17 17:53 UTC, maufcost submitted a review, later dismissed
LGTM! Great job!

2020-12-17 22:06 UTC, zachberry requested changes
This is working great but I'd like one minor optimization - On multiple attempts injectKatexIfNeeded will run multiple times and potentially inject katex multiple times. injectKatextIfNeeded could look for the presence of `window.katex` and finish right away if it already exists.

2021-01-14 18:26 UTC, zachberry approved these changes
LGTM!

2021-01-22 19:24 UTC, merged