Makes new assessments lock navigation by default
ucfopen/Obojobo pull request #1643
Opened 2021-01-06 20:32 UTC by jpeterson976

Resolves #1632

2021-01-07 14:18 UTC, maufcost submitted a review, later dismissed
LGTM! Good job!

2021-01-13 18:53 UTC, ctcuff approved these changes
Small suggestion below but besides that, everything looks good!

2021-01-13 18:53 UTC, ctcuff commented on packages/app/obojobo-document-engine/documents/empty.xml
> +			<triggers>
Minor style suggestion, not an expert on this but you could remove the empty value tag to simplify this a bit:
```xml
<triggers>
	<trigger type="onStartAttempt">
		<actions>
			<action type="nav:lock" />
		</actions>
	</trigger>
	<trigger type="onEndAttempt">
		<actions>
			<action type="nav:unlock" />
		</actions>
	</trigger>
</triggers>
```

2021-01-13 22:55 UTC, zachberry requested changes
(I merged in dev/16 to fix the snapshot timestamp issue)

I like @ctcuff 's suggestion - once that's addressed I'll give this the stamp of "LGTM"

2021-01-21 14:46 UTC, merged