Creates assessment:attemptInvalided event
ucfopen/Obojobo pull request #1656
Opened 2021-02-02 21:03 UTC by ctcuff

`insertEvent` is called after an assessment is invalidated. Fixes #1655

2021-02-03 18:28 UTC, zachberry commented
I made a tweak on this - I changed it so that it will only invalidate the attempt if it wasn't previously invalidated. That means only one event will be sent even if the student keeps attempting to submit the bad attempt

2021-02-04 13:24 UTC, maufcost approved these changes
This looks pretty good to me. Amazing job, Cam and Zac!

I tested with a bunch of assessment questions and rubrics, including updating questions and rubrics while a "student" (me) was taking the assessment. The modal saying that new updates were made to the assessment is so much better and worked with all the tests cases I used.

The only thing is that now obo shows the old error on the console, but it doesn't really hinder any new functionalities, so I believe this is good to go:
![Screen Shot 2021-02-04 at 10 20 15 AM](https://user-images.githubusercontent.com/39862359/106898539-b28dda80-66ca-11eb-8c2b-8affdb8b3812.png)

2021-02-05 20:00 UTC, iturgeon requested changes
Just a few comments code suggestions

2021-02-05 20:41 UTC, iturgeon approved these changes

2021-02-05 20:48 UTC, merged