Max-width option for figure captions
ucfopen/Obojobo pull request #1745
Opened 2021-03-24 18:00 UTC by jpeterson976

Resolves #1707 

Added a select box that lets you choose between image-width and max-width for figure captions. The default is image width, since that's the current behavior.

2021-03-30 19:59 UTC, zachberry requested changes
I didn't review the code but I did test it in the browser. I see it working in the editor but in doesn't seem to work in the viewer. Additionally it doesn't seem to be working for custom sizes (I tried 100x100)

2021-04-05 19:25 UTC, iturgeon requested changes
It looks like the viewer defaults to image-width for figures missing the caption width setting, the only thing not handling it is the style in the editor that results in `is-undefined` getting rendered to the dom.  We should either default to image-width or just avoid displaying the is-undefined at all

I expanded use of the image-width constants to everywhere they show up in this chunk.

2021-04-05 19:25 UTC, iturgeon commented on packages/obonode/obojobo-chunks-figure/image-properties-modal.test.js
> +			.find('#obojobo-draft--chunks--figure--caption-width')
👍

2021-04-05 19:25 UTC, iturgeon commented on packages/obonode/obojobo-chunks-figure/__snapshots__/editor-component.test.js.snap
> +exports[`Figure Editor Node Figure component handles tabbing 1`] = `"<div><div class=\\"obojobo-draft--chunks--figure viewer undefined  is-not-selected\\"><div contenteditable=\\"false\\" class=\\"ac
`is-undefined` seems undesirable here.  Does this indicate we need a default value in the editor component?

Keep in mind that previously created Figure chunks will render `is-undefined` like this sample

2021-04-06 14:27 UTC, zachberry requested changes
Looks great! I just have a few minor suggestions

2021-04-06 14:27 UTC, zachberry commented on packages/obonode/obojobo-chunks-figure/adapter.js
> +		model.setStateProp('captionWidth', ImageCaptionWidthTypes.IMAGE_WIDTH)
This should lower-case the attribute and ensure that it only be one of the two acceptable values:

```suggestion
		model.setStateProp('captionWidth', ImageCaptionWidthTypes.IMAGE_WIDTH, p => p.toLowerCase(), [ImageCaptionWidthTypes.IMAGE_WIDTH, ImageCaptionWidthTypes.MAX_WIDTH])
```

2021-04-06 14:27 UTC, zachberry commented on packages/obonode/obojobo-chunks-figure/viewer-component.js
> +							<figcaption className={`is-${captionWidth}`} style={captionStyle}>
I think we need to change this to `is-caption-width-${captionWidth}`

2021-04-06 17:29 UTC, zachberry approved these changes

2021-04-06 17:29 UTC, merged