Added loading spinners to dashboard
ucfopen/Obojobo pull request #1884
Opened 2021-07-19 17:56 UTC by maufcost

I re-used obo's spinner from `obojobo-document-engine`. Let me know if you would like me to re-design another one exclusively for the dashboard. The spinner is centered horizontally as requested and has a subtle margin from the top. As always, I am open for any changes.

Fixes #1849

2021-07-20 14:48 UTC, zachberry requested changes
This is working great! I'd like to add the same spinner to when modules are deleted as well (both bulk delete and deleting one module)

2021-07-22 17:52 UTC, jpeterson976 submitted a review, later dismissed
LGTM! Spinners are working for both creating and deleting modules. Good work!

2021-07-22 18:16 UTC, jpeterson976 commented
Also, this seems to cover #1853 as well

2021-07-29 16:05 UTC, zachberry requested changes
Looks great! Just have one code question for you

2021-07-29 16:05 UTC, zachberry commented on packages/app/obojobo-repository/shared/components/dashboard.scss
> +	.test {
Left in by mistake?

2021-07-29 16:26 UTC, maufcost commented on packages/app/obojobo-repository/shared/components/dashboard.scss
> +	.test {
Oh Christ. Yeah, I'm gonna remove that.

2021-07-29 18:18 UTC, zachberry approved these changes

2021-07-29 18:19 UTC, jpeterson976 approved these changes

2021-07-29 18:19 UTC, merged