Issue/1575 omit already shared
ucfopen/Obojobo pull request #1918
Opened 2021-10-05 21:36 UTC by walid-i

When sharing omits users that already have access

2021-10-29 20:18 UTC, FrenjaminBanklin requested changes
Looks good to me.

Just remove the large commented block from `packages/app/obojobo-repository/shared/components/people-search-dialog.jsx` and it should be all set.

2021-10-29 20:18 UTC, FrenjaminBanklin commented on packages/app/obojobo-repository/shared/components/people-search-dialog.jsx
> +					})} */}
Remove unused commented code.

2023-02-15 19:31 UTC, RachelDau commented
I merged in dev 30 except four style files which have lint errors. These lint errors appear to be already in dev30, so if I alter the files in order to commit them then they will continue to shop up on this PR diff. I was not sure if that was ideal so I didn't not commit those files yet. They show up in the diff right now without the dev30 merge updates.

2023-03-06 13:32 UTC, RachelDau commented
merged with Dev 30 and lint style updates made in 4 files. These four files more-info-box.scss, objective-list-view.scss, search.scss, and objective-item.scss are seperate from this PR, but needed their styles to be updated to be merged in. I also removed the commented code requested to be removed above.

2023-03-06 20:05 UTC, FrenjaminBanklin requested changes
Code isn't building to test, see below.

2023-03-21 15:43 UTC, FrenjaminBanklin approved these changes
Looks like this is working properly and performing as advertised.

2023-03-21 17:20 UTC, merged