Standardized clear filter button
ucfopen/Obojobo pull request #1934
Opened 2021-11-22 15:22 UTC by maufcost

I overrode `web-kit`'s UI for our clear filter button within obo's dashboard's search input, and everything seems to be standardized across Chrome, Safari, and Firefox.

Fixes #1930

2021-11-22 15:57 UTC, FrenjaminBanklin requested changes
This looks good, and it does the job.

Only thing I can think of - now that we have full control over how this looks, add a `cursor: pointer;` to round out the clickable button-ness of it.

It'd be nice if we could also make sure this shows up in Firefox, but it looks like that would require disabling the browser's pseudo-element and constructing our own instead. That will probably have to be its own issue.

2021-11-22 15:57 UTC, FrenjaminBanklin commented on packages/app/obojobo-repository/shared/components/search.scss
> +
```suggestion
			cursor: pointer;
```

2021-11-23 14:42 UTC, maufcost commented on packages/app/obojobo-repository/shared/components/search.scss
> +
Good call. Just added it.

2021-11-23 17:30 UTC, jpeterson976 submitted a review, later dismissed
Much more noticeable now on Chrome and Safari. Annoying that it just doesn't show up at all on Firefox, but like Brandon said that could probably become its own separate issue. LGTM!

2021-11-24 14:14 UTC, maufcost commented
I just found a solution for Firefox specifically. I will be committing that later today.

2021-11-29 14:32 UTC, maufcost commented
Everything seems to be working now on all three browsers. I'm just gonna be converting some measurement units from 'px' to 'em' for consistency now.

2021-11-30 16:12 UTC, FrenjaminBanklin approved these changes
Filter input now has a consistent clear button across all browsers.

Great work!

2021-11-30 16:26 UTC, jpeterson976 approved these changes
Worked in all 3 browsers, LGTM!

2021-11-30 16:27 UTC, merged