Issue/1929 module upload
ucfopen/Obojobo pull request #1936
Opened 2021-11-29 16:35 UTC by SJJacques

Test coverage is at 100%; Chrome can no longer upload `.svg` files and a window alert prompts the user if they attempt to upload one.

2021-11-30 19:13 UTC, FrenjaminBanklin approved these changes
Good job - straightforward and solves the problem.

2021-11-30 19:19 UTC, FrenjaminBanklin requested changes
Actually - I spoke too soon.

While this does prevent SVG files from being uploaded in Chrome, it appears to also be (sometimes) preventing XML files from being uploaded. Looks like the MIME type should be `text/xml` rather than `application/xml`.

Hopefully that'll just be a straightforward change.

2021-12-02 15:44 UTC, SJJacques commented
I've pushed the requisite changes and tested on Firefox, Chrome, and Safari. XML acceptance is now more permissive.

2021-12-02 16:08 UTC, FrenjaminBanklin requested changes
This looks like it's functionally complete, I just have a couple of very minor nits to pick with the code.

2021-12-02 16:08 UTC, FrenjaminBanklin commented on packages/app/obojobo-repository/shared/actions/dashboard-actions.test.js
> +	const XML_MIME_TYPE = 'application/xml'
Since there are now two valid XML mime types, make sure you test that both of them work.

2021-12-02 16:08 UTC, FrenjaminBanklin commented on packages/app/obojobo-repository/shared/actions/dashboard-actions.js
> +const XML_MIME_TYPE1 = 'text/xml'
I might prefer naming these `XML_MIME_TYPE_APPLICATION` and `XML_MIME_TYPE_TEXT` to be more descriptive.

2021-12-03 21:26 UTC, FrenjaminBanklin approved these changes
Looks good.

2021-12-06 20:42 UTC, deundrewilliams approved these changes
LGTM, the window alert works on Chrome and .svg files are greyed out in Firefox and Safari

2021-12-08 15:44 UTC, merged