Fixes LTI module picker not listing personal modules. Fixes module restoration crashes in dashboard.
ucfopen/Obojobo pull request #1991
Opened 2022-03-22 14:41 UTC by FrenjaminBanklin

Fixed LTI module selector not showing personal modules (or absence thereof). Fixed dashboard crashing in 'deleted' mode after restoring modules. Cleaned up unused/unnecessary state changes in dashboard reducer. Changed API call in dashboard action after restoring deleted modules. Adjusted tests re: actions/reducer changes.

2022-03-22 15:06 UTC, maufcost requested changes
Great work on this! Found one issue though. Instructions to replicate:

1) Create a couple modules on the dashboard
2) Select one of the modules
3) Click "Delete All"
4) The alert dialog will pop up. Just click cancel.
5) The animated loading indicator stays on the screen <--

2022-03-22 15:09 UTC, FrenjaminBanklin commented
Weird. I thought that was fixed in another PR. I must have un-fixed it in a bungled merge somewhere along the line.

Good catch, I'll figure that out.

2022-03-22 15:58 UTC, maufcost approved these changes
Awesome!

Personal modules are correctly displayed and the dashboard no longer crashes in 'deleted' mode after module restorations.

2022-03-29 16:31 UTC, jpeterson976 approved these changes
LGTM, I didn't notice any additional issues to fix.

2022-03-31 17:29 UTC, merged