issue/2026 Fixing Youtube Video Margins
ucfopen/Obojobo pull request #2029
Opened 2022-09-26 20:06 UTC by RachelDau

Added two CSS styles in viewer-component that reverse the applied margin styles to YouTube videos placed in Explanation and Feedback portions of the assessment chuck. This will stop the videos from being off center.

2022-09-27 13:44 UTC, deundrewilliams approved these changes
Tested locally and the changes lgtm

2022-10-11 16:08 UTC, FrenjaminBanklin requested changes
This addresses most of the issues, but it looks like the negative left padding is still occurring in feedback for numeric questions. Cover that case as well and this should be good to go.

I get the feeling there's the potential for a solution that doesn't require addressing YouTube chunks specifically, but otherwise this looks fine for now.

2022-10-12 13:46 UTC, FrenjaminBanklin commented
I suspect the text nodes have the negative margin to mitigate some kind of baseline padding so they align better along the left side of the container. Unless you find some scenario where the text actually escapes the left boundary, I'd leave it alone for now.

2022-11-07 17:14 UTC, RachelDau commented
<img width="631" alt="image" src="https://user-images.githubusercontent.com/112724541/200372258-f4da40aa-fdd6-4dda-8276-2f095a9a20a9.png">
Videos embedded in the question option body are uncentered, but I think this is ok because they line up on the left with the text. Should this also be adjusted?

2022-11-07 17:27 UTC, FrenjaminBanklin commented
The right border doesn't extend past the parent container so it's not -too- bad, but it would look better if it was centered properly.

Feel free to take a look, just be careful if the rule that's pushing the video off-center is also factored into the appearance of other things.

2022-11-07 18:53 UTC, RachelDau commented
Alright. Thank you. If you get a chance can you check out numeric questions feedback section videos because they appear to be centered on my end. I checked in firefox, chrome, and safari. Let me know if it still there and if you have any tips to reproduce the issue for me to look into.

2022-11-17 18:03 UTC, merged